remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: EMERALD\n1st Workshop on Distributed Computing with Emerging Hardware Technology

description: June 21th, 2024. Colocated with PODC and SPAA, Nantes, France.