remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: EMERALD <br/> 1st Workshop on Distributed Computing with Emerging Hardware Technology

description: 