title:  <img src="EMERALD.png" width="500" height="600"><br/> EMERALD <br/> 1st Workshop on Distributed Computing with Emerging Hardware Technology

description: June 21th, 2024. Colocated with PODC and SPAA 2024. Nantes, France.