remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: EMERALD workshop
description: In conjunction with PODC and SPAA, Nantes, France, June 17-21, 2024